"""Shared candidate-feature contract for live and offline dispatch scoring."""

from __future__ import annotations

SUPPORTED_CANDIDATE_FEATURES = (
    "travel_to_pickup_time",
    "travel_to_pickup_distance",
    "pickup_to_dropoff_time",
    "pickup_to_dropoff_distance",
    "pickup_node_inbound_degree",
    "pickup_node_outbound_degree",
    "dropoff_node_inbound_degree",
    "dropoff_node_outbound_degree",
    "travel_to_pickup_mean_transit_count",
    "travel_to_pickup_max_transit_count",
    "travel_to_pickup_mean_arc_traversal_count",
    "travel_to_pickup_max_arc_traversal_count",
    "pickup_to_dropoff_mean_transit_count",
    "pickup_to_dropoff_max_transit_count",
    "pickup_to_dropoff_mean_arc_traversal_count",
    "pickup_to_dropoff_max_arc_traversal_count",
    "task_age",
    "task_priority",
    "task_service_time_estimate",
    "robot_speed_multiplier",
    "robot_completed_task_count",
    "robot_total_busy_time",
    "robot_total_idle_time",
    "robot_total_travel_time",
    "robot_total_travel_distance",
    "pending_task_count",
    "ready_task_count",
    "future_task_count",
    "idle_robot_count",
    "busy_robot_count",
    "mean_ready_task_age",
    "average_robot_time_until_available",
    "active_reserved_edge_count",
    "active_reserved_node_count",
    "estimated_pickup_congestion_delay",
    "estimated_dropoff_congestion_delay",
    "estimated_pickup_blocked_segments",
    "estimated_dropoff_blocked_segments",
)
